// docsearch queries the Dyalog documentation database.
//
//	go build -tags "fts5" -o docsearch docsearch.go
package main

import (
	"bufio"
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	_ "github.com/mattn/go-sqlite3"
)

func defaultDBPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "dyalog-docs.db"
	}
	return filepath.Join(home, ".bundle-docs", "dyalog-docs.db")
}

func main() {
	dbPath := flag.String("d", defaultDBPath(), "database path")
	search := flag.String("s", "", "search string (use '-' to read from stdin)")
	rowid := flag.Int64("r", 0, "fetch document by rowid")
	limit := flag.Int("l", 10, "maximum number of results")
	flag.Parse()

	if *search == "" && *rowid == 0 {
		fmt.Fprintf(os.Stderr, `docsearch - search the Dyalog APL documentation database

This tool provides full-text search over the Dyalog APL documentation.
It covers language features, primitive functions and operators, system
functions, GUI references, and more.

USAGE
  docsearch -s <query>          Search for documents matching <query>
  docsearch -r <rowid>          Fetch the full content of a document by its rowid

WORKFLOW
  Searching is a two-step process:

  1. Search by keyword to get a list of matching documents:
       docsearch -s "index generator"
     Output (one per line): ROWID TITLE
       86 Index Generator R←⍳Y
       502 Search Functions and Hash Tables

  2. Fetch the full document content using the rowid from step 1:
       docsearch -r 86
     Output: the complete document text (markdown).

FLAGS
  -s <string>    Search query. Matches against keywords, titles, and content
                  (in that priority order). Use '-' to read from stdin.
  -r <rowid>     Fetch and print the full content of the document with this rowid.
  -l <limit>     Maximum number of search results (default: 10).
  -d <path>      Path to the SQLite database (default: %s).

SEARCH BEHAVIOUR
  Results are ranked in three tiers and deduplicated:
    1. Exact case-insensitive match on hidden search keywords
    2. FTS5 match on document title
    3. FTS5 match on document content
  The query is matched as a phrase. Use natural language terms, APL symbol
  names, or system function names (e.g. "⍳", "iota", "quad-IO", "⎕IO").

DATABASE
  The database is generated by bundle-docs. Run "bundle-docs update" to
  refresh it from the upstream Dyalog documentation repository.
`, defaultDBPath())
		os.Exit(1)
	}

	db, err := sql.Open("sqlite3", *dbPath)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	if *rowid != 0 {
		fetchByRowid(db, *rowid)
		return
	}

	query := *search
	if query == "-" {
		scanner := bufio.NewScanner(os.Stdin)
		if scanner.Scan() {
			query = scanner.Text()
		}
		if err := scanner.Err(); err != nil {
			log.Fatal(err)
		}
	}

	if query == "" {
		log.Fatal("empty search string")
	}

	searchDocs(db, query, *limit)
}

func fetchByRowid(db *sql.DB, rowid int64) {
	var content string
	err := db.QueryRow("SELECT content FROM docs WHERE rowid = ?", rowid).Scan(&content)
	if err == sql.ErrNoRows {
		log.Fatalf("no document with rowid %d", rowid)
	}
	if err != nil {
		log.Fatal(err)
	}
	fmt.Print(content)
}

func searchDocs(db *sql.DB, query string, limit int) {
	seen := make(map[int64]bool)
	count := 0

	// 1. Exact case-insensitive match on keywords
	rows, err := db.Query(`
		SELECT rowid, title FROM docs
		WHERE keywords LIKE ? COLLATE NOCASE AND exclude = 0
	`, "%"+query+"%")
	if err != nil {
		log.Fatal(err)
	}
	count = printResults(rows, seen, limit, count)
	if count >= limit {
		return
	}

	// 2. FTS search on title
	rows, err = db.Query(`
		SELECT f.rowid, f.title FROM docs_fts f
		JOIN docs d ON f.rowid = d.rowid
		WHERE f.title MATCH ? AND d.exclude = 0
	`, escapeQuery(query))
	if err != nil {
		log.Fatal(err)
	}
	count = printResults(rows, seen, limit, count)
	if count >= limit {
		return
	}

	// 3. FTS search on content
	rows, err = db.Query(`
		SELECT f.rowid, f.title FROM docs_fts f
		JOIN docs d ON f.rowid = d.rowid
		WHERE f.content MATCH ? AND d.exclude = 0
	`, escapeQuery(query))
	if err != nil {
		log.Fatal(err)
	}
	printResults(rows, seen, limit, count)
}

func printResults(rows *sql.Rows, seen map[int64]bool, limit, count int) int {
	defer rows.Close()
	for rows.Next() {
		if count >= limit {
			break
		}
		var rowid int64
		var title string
		if err := rows.Scan(&rowid, &title); err != nil {
			log.Fatal(err)
		}
		if seen[rowid] {
			continue
		}
		seen[rowid] = true
		fmt.Printf("%d %s\n", rowid, title)
		count++
	}
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
	return count
}

// escapeQuery wraps the query in quotes to handle special characters
func escapeQuery(q string) string {
	// Escape double quotes by doubling them
	q = strings.ReplaceAll(q, `"`, `""`)
	return `"` + q + `"`
}
